# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 2
from fastcore.foundation import patch
from fastcore.utils import *

# %% ../nbs/00_card.ipynb 5
suits = '♣ ♦ ♥ ♠'.split(' ')

# %% ../nbs/00_card.ipynb 6
ranks = [None, 'A'] + \
    [ str(i) for i in range(2,11) ] + \
    ['J', 'Q', 'K']

# %% ../nbs/00_card.ipynb 8
class Card:
    """
        A playing card.
    """
    def __init__(self, 
                 suit:int, # An index into `suits`
                 rank:int): # An index into `ranks`
        self.suit = suit 
        self.rank = rank
        
    def __str__(self):
        return (
            f'{ranks[self.rank]}'
            f'{suits[self.suit]}'
        )
    
    __repr__ = __str__

# %% ../nbs/00_card.ipynb 14
@patch
def __eq__(self:Card, c:Card):
    return ((self.suit, self.rank) == 
            (c.suit, c.rank))
@patch
def __lt__(self:Card, c:Card):
    return ((self.suit, self.rank) < 
            (c.suit, c.rank))
@patch
def __gt__(self:Card, c:Card):
    return ((self.suit, self.rank) >
            (c.suit, c.rank))
