# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/01_deck.ipynb 2
from fastcore.foundation import patch
from .card import *

# %% ../nbs/01_deck.ipynb 5
class Deck:
    """
        A deck of cards
        
        self.cards is a list of the cards available in the deck
        initially, the deck contains all cards
    """
    def __init__(self):        
        self.cards = [Card(s, r) for s in range(4) for r in range(1, 14)]
        
    def __len__(self): return len(self.cards)

    def __contains__(self, card): return card in self.cards
        
    def __str__(self): return '; '.join(map(str, self.cards))

    def __repr__(self): return self.__str__()
